// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ga_top,hls_ip_2018_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a12tcsg325-1q,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.662875,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=12,HLS_SYN_DSP=86,HLS_SYN_FF=4124,HLS_SYN_LUT=5753}" *)

module ga_top (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        start,
        result_finished_flag,
        result_best_x_V,
        result_best_y_V,
        result_best_desempen
);

parameter    ap_ST_fsm_state1 = 21'd1;
parameter    ap_ST_fsm_state2 = 21'd2;
parameter    ap_ST_fsm_state3 = 21'd4;
parameter    ap_ST_fsm_state4 = 21'd8;
parameter    ap_ST_fsm_state5 = 21'd16;
parameter    ap_ST_fsm_state6 = 21'd32;
parameter    ap_ST_fsm_state7 = 21'd64;
parameter    ap_ST_fsm_state8 = 21'd128;
parameter    ap_ST_fsm_state9 = 21'd256;
parameter    ap_ST_fsm_state10 = 21'd512;
parameter    ap_ST_fsm_state11 = 21'd1024;
parameter    ap_ST_fsm_state12 = 21'd2048;
parameter    ap_ST_fsm_state13 = 21'd4096;
parameter    ap_ST_fsm_state14 = 21'd8192;
parameter    ap_ST_fsm_state15 = 21'd16384;
parameter    ap_ST_fsm_state16 = 21'd32768;
parameter    ap_ST_fsm_state17 = 21'd65536;
parameter    ap_ST_fsm_state18 = 21'd131072;
parameter    ap_ST_fsm_state19 = 21'd262144;
parameter    ap_ST_fsm_state20 = 21'd524288;
parameter    ap_ST_fsm_state21 = 21'd1048576;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   start;
output  [0:0] result_finished_flag;
output  [27:0] result_best_x_V;
output  [27:0] result_best_y_V;
output  [27:0] result_best_desempen;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[0:0] result_finished_flag;

(* fsm_encoding = "none" *) reg   [20:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] seed;
reg   [7:0] populacao_x_V_address0;
reg    populacao_x_V_ce0;
reg    populacao_x_V_we0;
reg   [27:0] populacao_x_V_d0;
wire   [27:0] populacao_x_V_q0;
reg   [7:0] populacao_x_V_address1;
reg    populacao_x_V_ce1;
reg    populacao_x_V_we1;
wire   [27:0] populacao_x_V_q1;
reg   [7:0] populacao_y_V_address0;
reg    populacao_y_V_ce0;
reg    populacao_y_V_we0;
reg   [27:0] populacao_y_V_d0;
wire   [27:0] populacao_y_V_q0;
reg   [7:0] populacao_y_V_address1;
reg    populacao_y_V_ce1;
reg    populacao_y_V_we1;
wire   [27:0] populacao_y_V_q1;
reg   [7:0] populacao_desempenho_address0;
reg    populacao_desempenho_ce0;
reg    populacao_desempenho_we0;
reg   [27:0] populacao_desempenho_d0;
wire   [27:0] populacao_desempenho_q0;
reg   [7:0] populacao_desempenho_address1;
reg    populacao_desempenho_ce1;
reg    populacao_desempenho_we1;
wire   [27:0] populacao_desempenho_q1;
wire   [0:0] start_read_read_fu_136_p2;
wire   [7:0] i_4_fu_293_p2;
reg   [7:0] i_4_reg_677;
wire    ap_CS_fsm_state2;
reg   [10:0] rhs_V_i_i_reg_682;
wire   [0:0] exitcond_i_fu_287_p2;
reg   [10:0] rhs_V_i51_i_reg_687;
wire   [27:0] tmp_fu_391_p3;
reg   [27:0] tmp_reg_692;
wire    ap_CS_fsm_state3;
reg   [0:0] tmp_57_reg_697;
wire   [27:0] tmp_40_fu_407_p3;
reg   [27:0] tmp_40_reg_703;
reg   [0:0] tmp_61_reg_708;
wire    ap_CS_fsm_state4;
wire   [90:0] grp_fu_434_p2;
reg   [90:0] mul2_reg_724;
wire    ap_CS_fsm_state5;
reg   [18:0] tmp_59_reg_729;
wire   [90:0] grp_fu_451_p2;
reg   [90:0] mul_reg_735;
reg   [18:0] tmp_63_reg_740;
wire   [18:0] tmp_s_fu_504_p3;
reg   [18:0] tmp_s_reg_745;
wire    ap_CS_fsm_state6;
wire  signed [18:0] p_v9_v_fu_525_p3;
reg  signed [18:0] p_v9_v_reg_751;
wire   [27:0] neg_ti_fu_535_p2;
reg   [27:0] neg_ti_reg_756;
reg   [22:0] tmp_60_reg_761;
wire    ap_CS_fsm_state7;
reg   [22:0] tmp_66_reg_766;
wire   [4:0] i_5_fu_664_p2;
reg   [4:0] i_5_reg_774;
wire    ap_CS_fsm_state9;
wire    grp_mutacao_fu_229_ap_start;
wire    grp_mutacao_fu_229_ap_done;
wire    grp_mutacao_fu_229_ap_idle;
wire    grp_mutacao_fu_229_ap_ready;
wire   [31:0] grp_mutacao_fu_229_seed_o;
wire    grp_mutacao_fu_229_seed_o_ap_vld;
wire   [7:0] grp_mutacao_fu_229_populacao_x_V_address0;
wire    grp_mutacao_fu_229_populacao_x_V_ce0;
wire    grp_mutacao_fu_229_populacao_x_V_we0;
wire   [27:0] grp_mutacao_fu_229_populacao_x_V_d0;
wire   [7:0] grp_mutacao_fu_229_populacao_y_V_address0;
wire    grp_mutacao_fu_229_populacao_y_V_ce0;
wire    grp_mutacao_fu_229_populacao_y_V_we0;
wire   [27:0] grp_mutacao_fu_229_populacao_y_V_d0;
wire    grp_calcula_Desempenho_fu_239_ap_start;
wire    grp_calcula_Desempenho_fu_239_ap_done;
wire    grp_calcula_Desempenho_fu_239_ap_idle;
wire    grp_calcula_Desempenho_fu_239_ap_ready;
wire   [7:0] grp_calcula_Desempenho_fu_239_populacao_x_V_address0;
wire    grp_calcula_Desempenho_fu_239_populacao_x_V_ce0;
wire   [7:0] grp_calcula_Desempenho_fu_239_populacao_y_V_address0;
wire    grp_calcula_Desempenho_fu_239_populacao_y_V_ce0;
wire   [7:0] grp_calcula_Desempenho_fu_239_populacao_desempenho_address0;
wire    grp_calcula_Desempenho_fu_239_populacao_desempenho_ce0;
wire    grp_calcula_Desempenho_fu_239_populacao_desempenho_we0;
wire   [27:0] grp_calcula_Desempenho_fu_239_populacao_desempenho_d0;
wire    grp_reproducao_fu_249_ap_start;
wire    grp_reproducao_fu_249_ap_done;
wire    grp_reproducao_fu_249_ap_idle;
wire    grp_reproducao_fu_249_ap_ready;
wire   [31:0] grp_reproducao_fu_249_seed_o;
wire    grp_reproducao_fu_249_seed_o_ap_vld;
wire   [7:0] grp_reproducao_fu_249_populacao_x_V_address0;
wire    grp_reproducao_fu_249_populacao_x_V_ce0;
wire    grp_reproducao_fu_249_populacao_x_V_we0;
wire   [27:0] grp_reproducao_fu_249_populacao_x_V_d0;
wire   [7:0] grp_reproducao_fu_249_populacao_x_V_address1;
wire    grp_reproducao_fu_249_populacao_x_V_ce1;
wire   [7:0] grp_reproducao_fu_249_populacao_y_V_address0;
wire    grp_reproducao_fu_249_populacao_y_V_ce0;
wire    grp_reproducao_fu_249_populacao_y_V_we0;
wire   [27:0] grp_reproducao_fu_249_populacao_y_V_d0;
wire   [7:0] grp_reproducao_fu_249_populacao_y_V_address1;
wire    grp_reproducao_fu_249_populacao_y_V_ce1;
wire   [7:0] grp_reproducao_fu_249_populacao_desempenho_address0;
wire    grp_reproducao_fu_249_populacao_desempenho_ce0;
wire    grp_reproducao_fu_249_populacao_desempenho_we0;
wire   [27:0] grp_reproducao_fu_249_populacao_desempenho_d0;
wire   [7:0] grp_reproducao_fu_249_populacao_desempenho_address1;
wire    grp_reproducao_fu_249_populacao_desempenho_ce1;
wire    grp_bubble_sort_fu_261_ap_start;
wire    grp_bubble_sort_fu_261_ap_done;
wire    grp_bubble_sort_fu_261_ap_idle;
wire    grp_bubble_sort_fu_261_ap_ready;
wire   [7:0] grp_bubble_sort_fu_261_individuos_x_V_address0;
wire    grp_bubble_sort_fu_261_individuos_x_V_ce0;
wire    grp_bubble_sort_fu_261_individuos_x_V_we0;
wire   [27:0] grp_bubble_sort_fu_261_individuos_x_V_d0;
wire   [7:0] grp_bubble_sort_fu_261_individuos_x_V_address1;
wire    grp_bubble_sort_fu_261_individuos_x_V_ce1;
wire    grp_bubble_sort_fu_261_individuos_x_V_we1;
wire   [27:0] grp_bubble_sort_fu_261_individuos_x_V_d1;
wire   [7:0] grp_bubble_sort_fu_261_individuos_y_V_address0;
wire    grp_bubble_sort_fu_261_individuos_y_V_ce0;
wire    grp_bubble_sort_fu_261_individuos_y_V_we0;
wire   [27:0] grp_bubble_sort_fu_261_individuos_y_V_d0;
wire   [7:0] grp_bubble_sort_fu_261_individuos_y_V_address1;
wire    grp_bubble_sort_fu_261_individuos_y_V_ce1;
wire    grp_bubble_sort_fu_261_individuos_y_V_we1;
wire   [27:0] grp_bubble_sort_fu_261_individuos_y_V_d1;
wire   [7:0] grp_bubble_sort_fu_261_individuos_desempenh_address0;
wire    grp_bubble_sort_fu_261_individuos_desempenh_ce0;
wire    grp_bubble_sort_fu_261_individuos_desempenh_we0;
wire   [27:0] grp_bubble_sort_fu_261_individuos_desempenh_d0;
wire   [7:0] grp_bubble_sort_fu_261_individuos_desempenh_address1;
wire    grp_bubble_sort_fu_261_individuos_desempenh_ce1;
wire    grp_bubble_sort_fu_261_individuos_desempenh_we1;
wire   [27:0] grp_bubble_sort_fu_261_individuos_desempenh_d1;
reg   [7:0] i_i_reg_206;
wire    ap_CS_fsm_state8;
reg   [4:0] i_reg_218;
wire    ap_CS_fsm_state16;
reg    grp_mutacao_fu_229_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg    grp_calcula_Desempenho_fu_239_ap_start_reg;
wire   [0:0] exitcond_fu_658_p2;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state17;
reg    grp_reproducao_fu_249_ap_start_reg;
wire    ap_CS_fsm_state15;
reg    grp_bubble_sort_fu_261_ap_start_reg;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state19;
wire   [63:0] tmp_64_i_fu_652_p1;
wire   [31:0] seed_assign_i_fu_275_p2;
wire   [31:0] seed_assign_2_i_fu_325_p2;
wire    ap_CS_fsm_state21;
wire  signed [27:0] tmp_56_i_fu_644_p1;
wire    ap_CS_fsm_state20;
wire  signed [27:0] tmp_63_i_fu_648_p1;
wire   [31:0] p_Val2_11_fu_309_p2;
wire   [10:0] r_V_1_i_i_fu_337_p2;
wire   [27:0] retorno_V_fu_342_p3;
wire   [10:0] r_V_1_i52_i_fu_364_p2;
wire   [27:0] retorno_V_1_fu_369_p3;
wire   [0:0] tmp_55_fu_350_p3;
wire   [27:0] p_Val2_i_i_fu_358_p2;
wire   [0:0] tmp_56_fu_377_p3;
wire   [27:0] p_Val2_i56_i_fu_385_p2;
wire  signed [44:0] tmp_i_fu_423_p3;
wire   [46:0] grp_fu_434_p0;
wire  signed [44:0] tmp_58_i_fu_440_p3;
wire   [46:0] grp_fu_451_p0;
wire   [90:0] neg_mul3_fu_477_p2;
wire   [18:0] tmp_58_fu_482_p4;
wire   [18:0] p_v_v_fu_492_p3;
wire   [18:0] neg_ti8_fu_498_p2;
wire   [90:0] neg_mul_fu_510_p2;
wire   [18:0] tmp_62_fu_515_p4;
wire  signed [27:0] trunc_fu_531_p1;
wire   [53:0] tmp_39_fu_548_p3;
wire   [55:0] p_shl7_fu_541_p3;
wire  signed [55:0] p_shl8_fu_555_p1;
wire   [55:0] p_Val2_12_fu_559_p2;
wire  signed [56:0] tmp_54_i_cast_cast_fu_565_p1;
wire   [56:0] p_Val2_13_fu_569_p2;
wire  signed [27:0] tmp_41_fu_585_p1;
wire   [27:0] tmp_42_fu_588_p3;
wire   [18:0] tmp_64_fu_594_p1;
wire   [20:0] tmp_65_fu_606_p1;
wire   [55:0] p_shl_fu_598_p3;
wire   [55:0] p_shl6_fu_610_p3;
wire   [55:0] p_Val2_14_fu_618_p2;
wire  signed [56:0] tmp_61_i_cast_cast_fu_624_p1;
wire   [56:0] p_Val2_15_fu_628_p2;
reg   [20:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 21'd1;
#0 seed = 32'd1;
#0 grp_mutacao_fu_229_ap_start_reg = 1'b0;
#0 grp_calcula_Desempenho_fu_239_ap_start_reg = 1'b0;
#0 grp_reproducao_fu_249_ap_start_reg = 1'b0;
#0 grp_bubble_sort_fu_261_ap_start_reg = 1'b0;
end

ga_top_populacao_ibs #(
    .DataWidth( 28 ),
    .AddressRange( 200 ),
    .AddressWidth( 8 ))
populacao_x_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(populacao_x_V_address0),
    .ce0(populacao_x_V_ce0),
    .we0(populacao_x_V_we0),
    .d0(populacao_x_V_d0),
    .q0(populacao_x_V_q0),
    .address1(populacao_x_V_address1),
    .ce1(populacao_x_V_ce1),
    .we1(populacao_x_V_we1),
    .d1(grp_bubble_sort_fu_261_individuos_x_V_d1),
    .q1(populacao_x_V_q1)
);

ga_top_populacao_ibs #(
    .DataWidth( 28 ),
    .AddressRange( 200 ),
    .AddressWidth( 8 ))
populacao_y_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(populacao_y_V_address0),
    .ce0(populacao_y_V_ce0),
    .we0(populacao_y_V_we0),
    .d0(populacao_y_V_d0),
    .q0(populacao_y_V_q0),
    .address1(populacao_y_V_address1),
    .ce1(populacao_y_V_ce1),
    .we1(populacao_y_V_we1),
    .d1(grp_bubble_sort_fu_261_individuos_y_V_d1),
    .q1(populacao_y_V_q1)
);

ga_top_populacao_ibs #(
    .DataWidth( 28 ),
    .AddressRange( 200 ),
    .AddressWidth( 8 ))
populacao_desempenho_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(populacao_desempenho_address0),
    .ce0(populacao_desempenho_ce0),
    .we0(populacao_desempenho_we0),
    .d0(populacao_desempenho_d0),
    .q0(populacao_desempenho_q0),
    .address1(populacao_desempenho_address1),
    .ce1(populacao_desempenho_ce1),
    .we1(populacao_desempenho_we1),
    .d1(grp_bubble_sort_fu_261_individuos_desempenh_d1),
    .q1(populacao_desempenho_q1)
);

mutacao grp_mutacao_fu_229(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mutacao_fu_229_ap_start),
    .ap_done(grp_mutacao_fu_229_ap_done),
    .ap_idle(grp_mutacao_fu_229_ap_idle),
    .ap_ready(grp_mutacao_fu_229_ap_ready),
    .seed_i(seed),
    .seed_o(grp_mutacao_fu_229_seed_o),
    .seed_o_ap_vld(grp_mutacao_fu_229_seed_o_ap_vld),
    .populacao_x_V_address0(grp_mutacao_fu_229_populacao_x_V_address0),
    .populacao_x_V_ce0(grp_mutacao_fu_229_populacao_x_V_ce0),
    .populacao_x_V_we0(grp_mutacao_fu_229_populacao_x_V_we0),
    .populacao_x_V_d0(grp_mutacao_fu_229_populacao_x_V_d0),
    .populacao_x_V_q0(populacao_x_V_q0),
    .populacao_y_V_address0(grp_mutacao_fu_229_populacao_y_V_address0),
    .populacao_y_V_ce0(grp_mutacao_fu_229_populacao_y_V_ce0),
    .populacao_y_V_we0(grp_mutacao_fu_229_populacao_y_V_we0),
    .populacao_y_V_d0(grp_mutacao_fu_229_populacao_y_V_d0),
    .populacao_y_V_q0(populacao_y_V_q0)
);

calcula_Desempenho grp_calcula_Desempenho_fu_239(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_calcula_Desempenho_fu_239_ap_start),
    .ap_done(grp_calcula_Desempenho_fu_239_ap_done),
    .ap_idle(grp_calcula_Desempenho_fu_239_ap_idle),
    .ap_ready(grp_calcula_Desempenho_fu_239_ap_ready),
    .populacao_x_V_address0(grp_calcula_Desempenho_fu_239_populacao_x_V_address0),
    .populacao_x_V_ce0(grp_calcula_Desempenho_fu_239_populacao_x_V_ce0),
    .populacao_x_V_q0(populacao_x_V_q0),
    .populacao_y_V_address0(grp_calcula_Desempenho_fu_239_populacao_y_V_address0),
    .populacao_y_V_ce0(grp_calcula_Desempenho_fu_239_populacao_y_V_ce0),
    .populacao_y_V_q0(populacao_y_V_q0),
    .populacao_desempenho_address0(grp_calcula_Desempenho_fu_239_populacao_desempenho_address0),
    .populacao_desempenho_ce0(grp_calcula_Desempenho_fu_239_populacao_desempenho_ce0),
    .populacao_desempenho_we0(grp_calcula_Desempenho_fu_239_populacao_desempenho_we0),
    .populacao_desempenho_d0(grp_calcula_Desempenho_fu_239_populacao_desempenho_d0)
);

reproducao grp_reproducao_fu_249(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reproducao_fu_249_ap_start),
    .ap_done(grp_reproducao_fu_249_ap_done),
    .ap_idle(grp_reproducao_fu_249_ap_idle),
    .ap_ready(grp_reproducao_fu_249_ap_ready),
    .seed_i(seed),
    .seed_o(grp_reproducao_fu_249_seed_o),
    .seed_o_ap_vld(grp_reproducao_fu_249_seed_o_ap_vld),
    .populacao_x_V_address0(grp_reproducao_fu_249_populacao_x_V_address0),
    .populacao_x_V_ce0(grp_reproducao_fu_249_populacao_x_V_ce0),
    .populacao_x_V_we0(grp_reproducao_fu_249_populacao_x_V_we0),
    .populacao_x_V_d0(grp_reproducao_fu_249_populacao_x_V_d0),
    .populacao_x_V_q0(populacao_x_V_q0),
    .populacao_x_V_address1(grp_reproducao_fu_249_populacao_x_V_address1),
    .populacao_x_V_ce1(grp_reproducao_fu_249_populacao_x_V_ce1),
    .populacao_x_V_q1(populacao_x_V_q1),
    .populacao_y_V_address0(grp_reproducao_fu_249_populacao_y_V_address0),
    .populacao_y_V_ce0(grp_reproducao_fu_249_populacao_y_V_ce0),
    .populacao_y_V_we0(grp_reproducao_fu_249_populacao_y_V_we0),
    .populacao_y_V_d0(grp_reproducao_fu_249_populacao_y_V_d0),
    .populacao_y_V_q0(populacao_y_V_q0),
    .populacao_y_V_address1(grp_reproducao_fu_249_populacao_y_V_address1),
    .populacao_y_V_ce1(grp_reproducao_fu_249_populacao_y_V_ce1),
    .populacao_y_V_q1(populacao_y_V_q1),
    .populacao_desempenho_address0(grp_reproducao_fu_249_populacao_desempenho_address0),
    .populacao_desempenho_ce0(grp_reproducao_fu_249_populacao_desempenho_ce0),
    .populacao_desempenho_we0(grp_reproducao_fu_249_populacao_desempenho_we0),
    .populacao_desempenho_d0(grp_reproducao_fu_249_populacao_desempenho_d0),
    .populacao_desempenho_q0(populacao_desempenho_q0),
    .populacao_desempenho_address1(grp_reproducao_fu_249_populacao_desempenho_address1),
    .populacao_desempenho_ce1(grp_reproducao_fu_249_populacao_desempenho_ce1),
    .populacao_desempenho_q1(populacao_desempenho_q1)
);

bubble_sort grp_bubble_sort_fu_261(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bubble_sort_fu_261_ap_start),
    .ap_done(grp_bubble_sort_fu_261_ap_done),
    .ap_idle(grp_bubble_sort_fu_261_ap_idle),
    .ap_ready(grp_bubble_sort_fu_261_ap_ready),
    .individuos_x_V_address0(grp_bubble_sort_fu_261_individuos_x_V_address0),
    .individuos_x_V_ce0(grp_bubble_sort_fu_261_individuos_x_V_ce0),
    .individuos_x_V_we0(grp_bubble_sort_fu_261_individuos_x_V_we0),
    .individuos_x_V_d0(grp_bubble_sort_fu_261_individuos_x_V_d0),
    .individuos_x_V_q0(populacao_x_V_q0),
    .individuos_x_V_address1(grp_bubble_sort_fu_261_individuos_x_V_address1),
    .individuos_x_V_ce1(grp_bubble_sort_fu_261_individuos_x_V_ce1),
    .individuos_x_V_we1(grp_bubble_sort_fu_261_individuos_x_V_we1),
    .individuos_x_V_d1(grp_bubble_sort_fu_261_individuos_x_V_d1),
    .individuos_x_V_q1(populacao_x_V_q1),
    .individuos_y_V_address0(grp_bubble_sort_fu_261_individuos_y_V_address0),
    .individuos_y_V_ce0(grp_bubble_sort_fu_261_individuos_y_V_ce0),
    .individuos_y_V_we0(grp_bubble_sort_fu_261_individuos_y_V_we0),
    .individuos_y_V_d0(grp_bubble_sort_fu_261_individuos_y_V_d0),
    .individuos_y_V_q0(populacao_y_V_q0),
    .individuos_y_V_address1(grp_bubble_sort_fu_261_individuos_y_V_address1),
    .individuos_y_V_ce1(grp_bubble_sort_fu_261_individuos_y_V_ce1),
    .individuos_y_V_we1(grp_bubble_sort_fu_261_individuos_y_V_we1),
    .individuos_y_V_d1(grp_bubble_sort_fu_261_individuos_y_V_d1),
    .individuos_y_V_q1(populacao_y_V_q1),
    .individuos_desempenh_address0(grp_bubble_sort_fu_261_individuos_desempenh_address0),
    .individuos_desempenh_ce0(grp_bubble_sort_fu_261_individuos_desempenh_ce0),
    .individuos_desempenh_we0(grp_bubble_sort_fu_261_individuos_desempenh_we0),
    .individuos_desempenh_d0(grp_bubble_sort_fu_261_individuos_desempenh_d0),
    .individuos_desempenh_q0(populacao_desempenho_q0),
    .individuos_desempenh_address1(grp_bubble_sort_fu_261_individuos_desempenh_address1),
    .individuos_desempenh_ce1(grp_bubble_sort_fu_261_individuos_desempenh_ce1),
    .individuos_desempenh_we1(grp_bubble_sort_fu_261_individuos_desempenh_we1),
    .individuos_desempenh_d1(grp_bubble_sort_fu_261_individuos_desempenh_d1),
    .individuos_desempenh_q1(populacao_desempenho_q1)
);

ga_top_mul_47ns_4cud #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 47 ),
    .din1_WIDTH( 45 ),
    .dout_WIDTH( 91 ))
ga_top_mul_47ns_4cud_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_434_p0),
    .din1(tmp_i_fu_423_p3),
    .ce(1'b1),
    .dout(grp_fu_434_p2)
);

ga_top_mul_47ns_4cud #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 47 ),
    .din1_WIDTH( 45 ),
    .dout_WIDTH( 91 ))
ga_top_mul_47ns_4cud_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_451_p0),
    .din1(tmp_58_i_fu_440_p3),
    .ce(1'b1),
    .dout(grp_fu_451_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_bubble_sort_fu_261_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state13))) begin
            grp_bubble_sort_fu_261_ap_start_reg <= 1'b1;
        end else if ((grp_bubble_sort_fu_261_ap_ready == 1'b1)) begin
            grp_bubble_sort_fu_261_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_calcula_Desempenho_fu_239_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_state9) & (exitcond_fu_658_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state9) & (exitcond_fu_658_p2 == 1'd0)))) begin
            grp_calcula_Desempenho_fu_239_ap_start_reg <= 1'b1;
        end else if ((grp_calcula_Desempenho_fu_239_ap_ready == 1'b1)) begin
            grp_calcula_Desempenho_fu_239_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mutacao_fu_229_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_mutacao_fu_229_ap_start_reg <= 1'b1;
        end else if ((grp_mutacao_fu_229_ap_ready == 1'b1)) begin
            grp_mutacao_fu_229_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_reproducao_fu_249_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            grp_reproducao_fu_249_ap_start_reg <= 1'b1;
        end else if ((grp_reproducao_fu_249_ap_ready == 1'b1)) begin
            grp_reproducao_fu_249_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        i_i_reg_206 <= i_4_reg_677;
    end else if (((start_read_read_fu_136_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_i_reg_206 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond_i_fu_287_p2 == 1'd1))) begin
        i_reg_218 <= 5'd0;
    end else if (((grp_reproducao_fu_249_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        i_reg_218 <= i_5_reg_774;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond_i_fu_287_p2 == 1'd0))) begin
        seed <= seed_assign_2_i_fu_325_p2;
    end else if (((start_read_read_fu_136_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        seed <= seed_assign_i_fu_275_p2;
    end else if (((1'b1 == ap_CS_fsm_state16) & (grp_reproducao_fu_249_seed_o_ap_vld == 1'b1))) begin
        seed <= grp_reproducao_fu_249_seed_o;
    end else if (((1'b1 == ap_CS_fsm_state12) & (grp_mutacao_fu_229_seed_o_ap_vld == 1'b1))) begin
        seed <= grp_mutacao_fu_229_seed_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_4_reg_677 <= i_4_fu_293_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        i_5_reg_774 <= i_5_fu_664_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mul2_reg_724 <= grp_fu_434_p2;
        mul_reg_735 <= grp_fu_451_p2;
        tmp_59_reg_729 <= {{grp_fu_434_p2[90:72]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (tmp_61_reg_708 == 1'd1))) begin
        neg_ti_reg_756 <= neg_ti_fu_535_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p_v9_v_reg_751 <= p_v9_v_fu_525_p3;
        tmp_s_reg_745 <= tmp_s_fu_504_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond_i_fu_287_p2 == 1'd0))) begin
        rhs_V_i51_i_reg_687 <= {{p_Val2_11_fu_309_p2[11:1]}};
        rhs_V_i_i_reg_682 <= {{seed[11:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_40_reg_703[27 : 17] <= tmp_40_fu_407_p3[27 : 17];
        tmp_57_reg_697 <= tmp_fu_391_p3[32'd27];
        tmp_61_reg_708 <= tmp_40_fu_407_p3[32'd27];
        tmp_reg_692[27 : 17] <= tmp_fu_391_p3[27 : 17];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        tmp_60_reg_761 <= {{p_Val2_13_fu_569_p2[56:34]}};
        tmp_66_reg_766 <= {{p_Val2_15_fu_628_p2[56:34]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (tmp_61_reg_708 == 1'd0))) begin
        tmp_63_reg_740 <= {{grp_fu_451_p2[90:72]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        populacao_desempenho_address0 = 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_desempenho_address0 = grp_bubble_sort_fu_261_individuos_desempenh_address0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        populacao_desempenho_address0 = grp_reproducao_fu_249_populacao_desempenho_address0;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state10))) begin
        populacao_desempenho_address0 = grp_calcula_Desempenho_fu_239_populacao_desempenho_address0;
    end else begin
        populacao_desempenho_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_desempenho_address1 = grp_bubble_sort_fu_261_individuos_desempenh_address1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        populacao_desempenho_address1 = grp_reproducao_fu_249_populacao_desempenho_address1;
    end else begin
        populacao_desempenho_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        populacao_desempenho_ce0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_desempenho_ce0 = grp_bubble_sort_fu_261_individuos_desempenh_ce0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        populacao_desempenho_ce0 = grp_reproducao_fu_249_populacao_desempenho_ce0;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state10))) begin
        populacao_desempenho_ce0 = grp_calcula_Desempenho_fu_239_populacao_desempenho_ce0;
    end else begin
        populacao_desempenho_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_desempenho_ce1 = grp_bubble_sort_fu_261_individuos_desempenh_ce1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        populacao_desempenho_ce1 = grp_reproducao_fu_249_populacao_desempenho_ce1;
    end else begin
        populacao_desempenho_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_desempenho_d0 = grp_bubble_sort_fu_261_individuos_desempenh_d0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        populacao_desempenho_d0 = grp_reproducao_fu_249_populacao_desempenho_d0;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state10))) begin
        populacao_desempenho_d0 = grp_calcula_Desempenho_fu_239_populacao_desempenho_d0;
    end else begin
        populacao_desempenho_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_desempenho_we0 = grp_bubble_sort_fu_261_individuos_desempenh_we0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        populacao_desempenho_we0 = grp_reproducao_fu_249_populacao_desempenho_we0;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state10))) begin
        populacao_desempenho_we0 = grp_calcula_Desempenho_fu_239_populacao_desempenho_we0;
    end else begin
        populacao_desempenho_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_desempenho_we1 = grp_bubble_sort_fu_261_individuos_desempenh_we1;
    end else begin
        populacao_desempenho_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        populacao_x_V_address0 = 8'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        populacao_x_V_address0 = tmp_64_i_fu_652_p1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_x_V_address0 = grp_bubble_sort_fu_261_individuos_x_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        populacao_x_V_address0 = grp_reproducao_fu_249_populacao_x_V_address0;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state10))) begin
        populacao_x_V_address0 = grp_calcula_Desempenho_fu_239_populacao_x_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        populacao_x_V_address0 = grp_mutacao_fu_229_populacao_x_V_address0;
    end else begin
        populacao_x_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_x_V_address1 = grp_bubble_sort_fu_261_individuos_x_V_address1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        populacao_x_V_address1 = grp_reproducao_fu_249_populacao_x_V_address1;
    end else begin
        populacao_x_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state8))) begin
        populacao_x_V_ce0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_x_V_ce0 = grp_bubble_sort_fu_261_individuos_x_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        populacao_x_V_ce0 = grp_reproducao_fu_249_populacao_x_V_ce0;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state10))) begin
        populacao_x_V_ce0 = grp_calcula_Desempenho_fu_239_populacao_x_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        populacao_x_V_ce0 = grp_mutacao_fu_229_populacao_x_V_ce0;
    end else begin
        populacao_x_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_x_V_ce1 = grp_bubble_sort_fu_261_individuos_x_V_ce1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        populacao_x_V_ce1 = grp_reproducao_fu_249_populacao_x_V_ce1;
    end else begin
        populacao_x_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        populacao_x_V_d0 = tmp_56_i_fu_644_p1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_x_V_d0 = grp_bubble_sort_fu_261_individuos_x_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        populacao_x_V_d0 = grp_reproducao_fu_249_populacao_x_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        populacao_x_V_d0 = grp_mutacao_fu_229_populacao_x_V_d0;
    end else begin
        populacao_x_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        populacao_x_V_we0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_x_V_we0 = grp_bubble_sort_fu_261_individuos_x_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        populacao_x_V_we0 = grp_reproducao_fu_249_populacao_x_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        populacao_x_V_we0 = grp_mutacao_fu_229_populacao_x_V_we0;
    end else begin
        populacao_x_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_x_V_we1 = grp_bubble_sort_fu_261_individuos_x_V_we1;
    end else begin
        populacao_x_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        populacao_y_V_address0 = 8'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        populacao_y_V_address0 = tmp_64_i_fu_652_p1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_y_V_address0 = grp_bubble_sort_fu_261_individuos_y_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        populacao_y_V_address0 = grp_reproducao_fu_249_populacao_y_V_address0;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state10))) begin
        populacao_y_V_address0 = grp_calcula_Desempenho_fu_239_populacao_y_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        populacao_y_V_address0 = grp_mutacao_fu_229_populacao_y_V_address0;
    end else begin
        populacao_y_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_y_V_address1 = grp_bubble_sort_fu_261_individuos_y_V_address1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        populacao_y_V_address1 = grp_reproducao_fu_249_populacao_y_V_address1;
    end else begin
        populacao_y_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state8))) begin
        populacao_y_V_ce0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_y_V_ce0 = grp_bubble_sort_fu_261_individuos_y_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        populacao_y_V_ce0 = grp_reproducao_fu_249_populacao_y_V_ce0;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state10))) begin
        populacao_y_V_ce0 = grp_calcula_Desempenho_fu_239_populacao_y_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        populacao_y_V_ce0 = grp_mutacao_fu_229_populacao_y_V_ce0;
    end else begin
        populacao_y_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_y_V_ce1 = grp_bubble_sort_fu_261_individuos_y_V_ce1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        populacao_y_V_ce1 = grp_reproducao_fu_249_populacao_y_V_ce1;
    end else begin
        populacao_y_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        populacao_y_V_d0 = tmp_63_i_fu_648_p1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_y_V_d0 = grp_bubble_sort_fu_261_individuos_y_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        populacao_y_V_d0 = grp_reproducao_fu_249_populacao_y_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        populacao_y_V_d0 = grp_mutacao_fu_229_populacao_y_V_d0;
    end else begin
        populacao_y_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        populacao_y_V_we0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_y_V_we0 = grp_bubble_sort_fu_261_individuos_y_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        populacao_y_V_we0 = grp_reproducao_fu_249_populacao_y_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        populacao_y_V_we0 = grp_mutacao_fu_229_populacao_y_V_we0;
    end else begin
        populacao_y_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state14))) begin
        populacao_y_V_we1 = grp_bubble_sort_fu_261_individuos_y_V_we1;
    end else begin
        populacao_y_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((start_read_read_fu_136_p2 == 1'd1)) begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            result_finished_flag = 1'd1;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            result_finished_flag = 1'd0;
        end else begin
            result_finished_flag = 1'd0;
        end
    end else begin
        result_finished_flag = 1'd0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((start_read_read_fu_136_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((start_read_read_fu_136_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (exitcond_i_fu_287_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (exitcond_fu_658_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_calcula_Desempenho_fu_239_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (grp_mutacao_fu_229_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_bubble_sort_fu_261_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((grp_reproducao_fu_249_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((1'b1 == ap_CS_fsm_state17) & (grp_calcula_Desempenho_fu_239_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((grp_bubble_sort_fu_261_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign exitcond_fu_658_p2 = ((i_reg_218 == 5'd20) ? 1'b1 : 1'b0);

assign exitcond_i_fu_287_p2 = ((i_i_reg_206 == 8'd200) ? 1'b1 : 1'b0);

assign grp_bubble_sort_fu_261_ap_start = grp_bubble_sort_fu_261_ap_start_reg;

assign grp_calcula_Desempenho_fu_239_ap_start = grp_calcula_Desempenho_fu_239_ap_start_reg;

assign grp_fu_434_p0 = 91'd35185059443828;

assign grp_fu_451_p0 = 91'd35185059443828;

assign grp_mutacao_fu_229_ap_start = grp_mutacao_fu_229_ap_start_reg;

assign grp_reproducao_fu_249_ap_start = grp_reproducao_fu_249_ap_start_reg;

assign i_4_fu_293_p2 = (i_i_reg_206 + 8'd1);

assign i_5_fu_664_p2 = (i_reg_218 + 5'd1);

assign neg_mul3_fu_477_p2 = (91'd0 - mul2_reg_724);

assign neg_mul_fu_510_p2 = (91'd0 - mul_reg_735);

assign neg_ti8_fu_498_p2 = (19'd0 - p_v_v_fu_492_p3);

assign neg_ti_fu_535_p2 = ($signed(28'd0) - $signed(trunc_fu_531_p1));

assign p_Val2_11_fu_309_p2 = (32'd5000000 + seed);

assign p_Val2_12_fu_559_p2 = ($signed(p_shl7_fu_541_p3) + $signed(p_shl8_fu_555_p1));

assign p_Val2_13_fu_569_p2 = ($signed(57'd132856189007429632) + $signed(tmp_54_i_cast_cast_fu_565_p1));

assign p_Val2_14_fu_618_p2 = (p_shl_fu_598_p3 + p_shl6_fu_610_p3);

assign p_Val2_15_fu_628_p2 = ($signed(57'd132856189007429632) + $signed(tmp_61_i_cast_cast_fu_624_p1));

assign p_Val2_i56_i_fu_385_p2 = (28'd0 - retorno_V_1_fu_369_p3);

assign p_Val2_i_i_fu_358_p2 = (28'd0 - retorno_V_fu_342_p3);

assign p_shl6_fu_610_p3 = {{tmp_65_fu_606_p1}, {35'd0}};

assign p_shl7_fu_541_p3 = {{tmp_s_reg_745}, {37'd0}};

assign p_shl8_fu_555_p1 = $signed(tmp_39_fu_548_p3);

assign p_shl_fu_598_p3 = {{tmp_64_fu_594_p1}, {37'd0}};

assign p_v9_v_fu_525_p3 = ((tmp_61_reg_708[0:0] === 1'b1) ? tmp_62_fu_515_p4 : tmp_63_reg_740);

assign p_v_v_fu_492_p3 = ((tmp_57_reg_697[0:0] === 1'b1) ? tmp_58_fu_482_p4 : tmp_59_reg_729);

assign r_V_1_i52_i_fu_364_p2 = (11'd980 - rhs_V_i51_i_reg_687);

assign r_V_1_i_i_fu_337_p2 = (11'd980 - rhs_V_i_i_reg_682);

assign result_best_desempen = populacao_desempenho_q0;

assign result_best_x_V = populacao_x_V_q0;

assign result_best_y_V = populacao_y_V_q0;

assign retorno_V_1_fu_369_p3 = {{r_V_1_i52_i_fu_364_p2}, {17'd0}};

assign retorno_V_fu_342_p3 = {{r_V_1_i_i_fu_337_p2}, {17'd0}};

assign seed_assign_2_i_fu_325_p2 = (32'd10000000 + seed);

assign seed_assign_i_fu_275_p2 = (seed + 32'd5010000);

assign start_read_read_fu_136_p2 = start;

assign tmp_39_fu_548_p3 = {{tmp_s_reg_745}, {35'd0}};

assign tmp_40_fu_407_p3 = ((tmp_56_fu_377_p3[0:0] === 1'b1) ? p_Val2_i56_i_fu_385_p2 : retorno_V_1_fu_369_p3);

assign tmp_41_fu_585_p1 = p_v9_v_reg_751;

assign tmp_42_fu_588_p3 = ((tmp_61_reg_708[0:0] === 1'b1) ? neg_ti_reg_756 : tmp_41_fu_585_p1);

assign tmp_54_i_cast_cast_fu_565_p1 = $signed(p_Val2_12_fu_559_p2);

assign tmp_55_fu_350_p3 = r_V_1_i_i_fu_337_p2[32'd10];

assign tmp_56_fu_377_p3 = r_V_1_i52_i_fu_364_p2[32'd10];

assign tmp_56_i_fu_644_p1 = $signed(tmp_60_reg_761);

assign tmp_58_fu_482_p4 = {{neg_mul3_fu_477_p2[90:72]}};

assign tmp_58_i_fu_440_p3 = {{tmp_40_reg_703}, {17'd0}};

assign tmp_61_i_cast_cast_fu_624_p1 = $signed(p_Val2_14_fu_618_p2);

assign tmp_62_fu_515_p4 = {{neg_mul_fu_510_p2[90:72]}};

assign tmp_63_i_fu_648_p1 = $signed(tmp_66_reg_766);

assign tmp_64_fu_594_p1 = tmp_42_fu_588_p3[18:0];

assign tmp_64_i_fu_652_p1 = i_i_reg_206;

assign tmp_65_fu_606_p1 = tmp_42_fu_588_p3[20:0];

assign tmp_fu_391_p3 = ((tmp_55_fu_350_p3[0:0] === 1'b1) ? p_Val2_i_i_fu_358_p2 : retorno_V_fu_342_p3);

assign tmp_i_fu_423_p3 = {{tmp_reg_692}, {17'd0}};

assign tmp_s_fu_504_p3 = ((tmp_57_reg_697[0:0] === 1'b1) ? neg_ti8_fu_498_p2 : tmp_59_reg_729);

assign trunc_fu_531_p1 = p_v9_v_fu_525_p3;

always @ (posedge ap_clk) begin
    tmp_reg_692[16:0] <= 17'b00000000000000000;
    tmp_40_reg_703[16:0] <= 17'b00000000000000000;
end

endmodule //ga_top
